language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - cp development/travis/config.php tests/config.php
  - mysql -e 'create database ilch2_test;'
  - composer install

script: cd tests && ../vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - http://www.ilch.de/ilch2/versions/
    on_success: always
    on_failure: never
    on_start: false
