services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - mysql -e 'CREATE DATABASE ilch2_test;'
install:
  - cp development/travis/config.php tests/config.php
  - composer install --prefer-dist

script: cd tests && ../vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - http://www.ilch.de/ilch2/versions/
    on_success: always
    on_failure: never
    on_start: false
